version: \"3.8\"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - \"3000:80\"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - \"5000:5000\"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Replace with your actual API key
      - GEMINI_API_KEY=${GEMINI_API_KEY}  # Replace with your actual API key, if used
    volumes:
      - backend_data:/app/data #This is optional, if you want persistant local storage
volumes:
  backend_data: